language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - cp phpunit.xml.dist phpunit.xml
    - composer self-update
    - composer install --dev

script: phpunit -c phpunit.xml --coverage-text

before_install:
    - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
